{% set name = "georouting" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/georouting-{{ version }}.tar.gz
  sha256: 6a06613e5fd8bbb23fcab61c54c17f66832ac50c20da96f709504de1a5abbc0b

build:
  entry_points:
    - georouting=georouting.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - python-igraph
    - osmnx
    - polyline
    - googlemaps
    - geopandas
    - folium
    - mapclassify
    - matplotlib-base

test:
  imports:
    - georouting
  commands:
    - pip check
    - georouting --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wybert/georouting
  summary: Geo routing for Python users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wybert
